### ISSUE TITLE
cp: cannot stat 'node_modules/php-wasm/php-web-drupal.*': No such file or directory

### ISSUE THREAD

**Issue by kenorb** [seanmorris/php-wasm#10]
The following error happens in `docs-source/` when running `npm install`:

```
docs-source$ npm install

> php-wasm-doc@0.0.0 postinstall
> cp -rfv node_modules/php-wasm/php-web.* app/assets/; cp -rfv node_modules/php-wasm/php-web-drupal.* app/assets/

'node_modules/php-wasm/php-web.data' -> 'app/assets/php-web.data'
'node_modules/php-wasm/php-web.js' -> 'app/assets/php-web.js'
'node_modules/php-wasm/php-web.wasm' -> 'app/assets/php-web.wasm'
cp: cannot stat 'node_modules/php-wasm/php-web-drupal.*': No such file or directory
npm ERR! code 1
npm ERR! path docs-source
npm ERR! command failed
npm ERR! command sh -c cp -rfv node_modules/php-wasm/php-web.* app/assets/; cp -rfv node_modules/php-wasm/php-web-drupal.* app/assets/

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2022-02-26T23_36_11_739Z-debug.log
```

Maybe it's because `php-web-drupal.*` files aren't included in the package.

Upgrading to `0.0.4-b` didn't help.

**Comment by seanmorris** [comment]
Looks like you're trying to install the doc site. Thats a static application that uses PHP-WASM. Try using the same command in the project root.

**Comment by seanmorris** [comment]
I deleted my previous comment as I'm a little confused. The docs-source/ directory contains an application that is served through github pages as an example useage of the project.

Are you trying to build that application? Or would you like to build the main project instead?

**Comment by kenorb** [comment]
> Are you trying to build that application?

Yes, I've tried to build the application which was on GitHub Pages to reproduce it.
I've noticed your recent changes, and it now `npm install` dependencies correctly, thanks.
