### ISSUE TITLE
Plans to incorporate the WASI spec?

### ISSUE THREAD

**Issue by technosophos** [seanmorris/php-wasm#13]
Do you have any plans on building a version to target wasm32-wasi? There is some interest in the [Twitter WebAssembly community](https://twitter.com/i/communities/1497545442023944192) in running PHP in [Spin](https://spin.fermyon.dev/) or other server-side platforms

**Comment by seanmorris** [comment]
Can you provide some more info on WASI?

**Comment by vados-cosmonic** [comment]
Hey @seanmorris sorry to necrobump this (a new issue/discussion is also fine!) but some more info on WASI, just in case you need it :)

[WASI main page](https://wasi.dev/)

[The Component Model book which does more explaining at a high level](https://component-model.bytecodealliance.org/) (works with but not *required* for WASI support)

[WebAssembly Interface Types](https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md)

[WASI repo](https://github.com/WebAssembly/WASI)
[WASI Preview 2 interfaces](https://github.com/WebAssembly/WASI/tree/main/wasip2) (Example [`wasi:filesystem/types#descriptor.read` reading from a file descriptor](https://github.com/WebAssembly/WASI/blob/main/wasip2/filesystem/types.wit#L410))

As a sort of quick explanation, WASI serves as an embedding for standardized system functionality that works outside the browser (and *[inside* it too](https://github.com/bjorn3/browser_wasi_shim)).
