### ISSUE TITLE
Module not found: Can't resolve 'asm2wasm'

### ISSUE THREAD

**Issue by kenorb** [seanmorris/php-wasm#17]
> Module not found: Can't resolve 'asm2wasm' in node_modules/php-wasm

It happens when I'm trying to run `PhpWebDrupal` in the app by:

```
const PhpWebDrupal = (await require('php-wasm/PhpWebDrupal')).PhpWebDrupal;
```

In comparison, PhpWeb is loading without this error.

**Comment by seanmorris** [comment]
@kenorb Are you using a bundler?

**Comment by kenorb** [comment]
Using php-wasm v0.0.5 in NextJS as part of this [repo](Drupal8-demo).

Here is the line which I'm changing to `PhpWebDrupal`:

https://github.com/mycognitive/Drupal8-demo/blob/221920d60bc84095c49ba5fb6c130fbcb4b713e9/src/components/Drupal.js#L13

**Comment by seanmorris** [comment]
Are you waiting for `ready` to fire?

```javascript
php.addEventListener('ready', () => {
	php.run('<?php echo "Hello, world!";');
});
```

**Comment by kenorb** [comment]
Tested with `ready` state, same error. Works for PhpWeb, but not for PhpWebDrupal.
It's possible that this can be Next.js specific, and it has trouble loading code in PhpWebDrupal.js properly.

**Comment by seanmorris** [comment]
Hmmm, on a hunch, does it work if you await require the asm2wasm module before the php-wasm module?
