### ISSUE TITLE
PhpWeb returnValue: -1

### ISSUE THREAD

**Issue by kenorb** [seanmorris/php-wasm#18]
I'm trying to test PhpWeb inside NextJS, and it loads fine, but PhpWeb returns -1 error when running PHP code.

My code in brief:
```
PhpWeb = (await require('php-wasm/PhpWeb')).PhpWeb;
php = new PhpWeb;
console.log(php.run('<?php echo "Hello, world!";').retVal);
```

I don't have any obvious errors, it's just PhpWeb instance returns code -1 (`{"returnValue": -1, "binary": {}}`).

Are there any additional steps before running the code for the first time? Or any other way to debug the reason of the error?

I'm using the latest available version of php-wasm (`0.0.5`).

**Comment by kenorb** [comment]
I've tried:

    console.log(php.run('<?php echo "Hello, world!";').then(retVal => { console.log('retVal: ', retVal); }));

and retVal is zero now, but no sign of Hello text.

Results:
```
Promise {<pending>}
retVal:  0
```

Any suggestion how to return the echo'ed string?

**Comment by seanmorris** [comment]
You might also want to wait for READY before you call RUN:

```javascript
php.addEventListener('ready', () => {
	php.run('<?php echo "Hello, world!";');
});
```

**Comment by seanmorris** [comment]
@kenorb are we able to close this issue?

**Comment by kenorb** [comment]
Sure, the original issue has been solved. I'm going to do more testing as per suggestion.
