### ISSUE TITLE
Package files missing

### ISSUE THREAD

**Issue by kenorb** [seanmorris/php-wasm#21]
Package file defines files such `php-web.js`, but this file isn't part of this repository.
Can you include these files, or they're part of another repository? Should I look into [`oraoto/pib`](https://github.com/oraoto/pib) repo instead?
Also, all files are minimalized, maybe it's more useful to include the original files with their original formatting? Then minimalize then on build? Otherwise there is no easy way to propose any new changes (against files which are missing or minimalized versions).

**Comment by seanmorris** [comment]
Those are build artifacts, which I usually try not to commit to a source repository. They files are all available in the npm package, as well as on [unpkg](https://unpkg.com/browse/php-wasm), though. The package is a little large, so you might need to refresh unpkg if the link errors out the first time.

Does that give you what you need?
