### ISSUE TITLE
php 8.3 support

### ISSUE THREAD

**Issue by liudonghua123** [seanmorris/php-wasm#35]
Hi, [php-8.3.0](https://www.php.net/releases/8.3/en.php) is released, and it contains many new features, such as explicit typing of class constants, deep-cloning of readonly properties and additions to the randomness functionality. As always it also includes performance improvements, bug fixes, and general cleanup.

Could you update the code and related packages?

See also https://github.com/php/php-src/tree/PHP-8.3.0.

**Comment by soyuka** [comment]
I think there are a few issues in the build system of this repository (we don't need to patch php + docker is misused) my fork compiles php 8.3 already at https://github.com/soyuka/php-wasm/ just change the PHP_BRANCH. 

@seanmorris maybe that I could provide my build improvements to your fork? Let me know.

**Comment by seanmorris** [comment]
Version 0.0.9 is in alpha, and includes php 8.3, as well as a bunch of extensions:

![image](https://github.com/seanmorris/php-wasm/assets/640101/86ab29d6-f0f6-4274-8b87-a21f1a97fb7d)
