### ISSUE TITLE
Global install results in "No rule to make target 'image'" error

### ISSUE THREAD

**Issue by ashooner** [seanmorris/php-wasm#38]
To recreate, follow the readme instructions for build in place:

1. `$ npm install -g php-wasm` (completes successfully)

2. `$ php-wasm image`

results in:
`make: *** No rule to make target 'image'.  Stop.`

I've tried this on a MacOS host as well as a default gitpod workspace container with the same result.

**Comment by ATLAbanana35** [comment]
Me too

**Comment by jbreuer95** [comment]
same

**Comment by kazzkzpk** [comment]
Me too :(

**Comment by seanmorris** [comment]
@ATLAbanana35 @jbreuer95 @kazzkzpk Sorry for the misstep there! You'll need to use the `php-wasm-builder` package for that. Things were getting a little too big for CDNs like unpkg & jsdeliver, so I had to break things up, but everything is still in one github repository.

The readme has been updated!
