### ISSUE TITLE
Publishing latest version on npm with node build

### ISSUE THREAD

**Issue by lubomirblazekcz** [seanmorris/php-wasm#6]
https://www.npmjs.com/package/php-wasm

Latest version on npm is 0.0.1-b and there is no build for node. Would love to try this and run php in nodejs.

**Comment by notdefine** [comment]
Hi evromalarkey,

the npmjs package is based on oraoto/pib, not on this branch. So, you must compile (this repository) and add the compiled files by hand.

I just had some fun with PHP in Browser with https://gitlab.com/notdefine/php-wasm-frontend-framework

greeting Thomas

**Comment by seanmorris** [comment]
https://www.npmjs.com/package/php-wasm

I've published the latest version which runs PHP 7.4.20. Sorry it took so long, I haven't had much time for this project lately but I should be able to keep an eye on it now.

Let me know how it runs.
