### ISSUE TITLE
Mismatch with npmjs site

### ISSUE THREAD

**Issue by kenorb** [seanmorris/php-wasm#9]
At https://www.npmjs.com/package/php-wasm when clicking on Repository ([github.com/seanmorris/pib](https://github.com/seanmorris/pib)), it redirects to this repository, but this repository doesn't have `0.0.4-b` version.
Is this expected?

Where is the latest tagged code? This repo has only `v0.0.01b`.

**Comment by seanmorris** [comment]
I've tagged the latest version 0.0.5, which aligns with npm. Sorry for any confusion.
